default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 2
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: 
  database: osago

test:
  <<: *default
  database: osago_test

production:
  <<: *default
  database: osago_production
