Car.create!(title: 'Мотоциклы, мопеды и легкие квадрициклы (транспортные средства категории "A", "M")', rate: 867, rate_max:1579, tractor: false,  trailer_rate: 1.16 )
Car.create!(title: 'Легковые автомобили для физических лиц(категории В)', rate: 3432, rate_max: 4118, tractor: false, trailer_rate: 1 )
Car.create!(title: 'Легковые автомобили для юридических лиц(категории В)', rate: 2573, rate_max: 3087, tractor: false, trailer_rate:1.16)
Car.create!(title: 'Легковые автомобили спользуемые в качестве такси', rate: 5138, rate_max: 6166, tractor: false, trailer_rate: 1)
Car.create!(title: 'Грузовые автомобили < 16 тонн (категории С)', rate: 3509, rate_max: 4211, tractor: false, trailer_rate: 1.40)
Car.create!(title: 'Грузовые автомобили > 16 тонн (категории С)', rate: 5284, rate_max: 6341, tractor: false, trailer_rate: 1.25)
Car.create!(title: 'Тракторы, самоходные дорожно-строительные и иные машины', rate: 1124, rate_max:1579, tractor: true, trailer_rate: 1.24)

City.create!(name: 'Барнаул', car_rate:	1.7, tractor_rate: 1)
City.create!(name: 'Вологда', car_rate:	1.7, tractor_rate: 1)
City.create!(name: 'Чита', car_rate:	1.1, tractor_rate: 0.8)
City.create!(name: 'Калуга', car_rate:	1.2, tractor_rate: 0.8)
City.create!(name: 'Орел', car_rate:	1.2, tractor_rate: 0.8)
City.create!(name: 'Ухта', car_rate:	1.3, tractor_rate: 0.8)

CarHorsePower.create!(description: 'До 50 л.с. включительно', rate: 0.6)
CarHorsePower.create!(description: 'от 51 до 70 включительно', rate: 1.0)
CarHorsePower.create!(description: 'от 71 до 100 включительно', rate: 1.1)
CarHorsePower.create!(description: 'от 101 до 120 включительно', rate: 1.2)
CarHorsePower.create!(description: 'от 121 до 150 включительно', rate: 1.4)
CarHorsePower.create!(description: 'от 151', rate: 1.6)
